language: go
sudo: false
matrix:
  include:
  - go: tip
  allow_failures:
  - go: tip
script:
- ".travis/build-all"
- go get golang.org/x/tools/cmd/cover
- go test -coverprofile fmt
deploy:
  provider: releases
  api_key:
    secure: hJp8XqG4Yfds+7LiqiYkMjhbLsAE+T+VUKib3+77kNFZ9kfYnTg5UKGKJN9L6/RupNkVX9QpQKfduRGycqU1DSNqWXycadk3YV6f8hnI08auWr+jzS2Re74JK2HAqgi6Bec2pGquejAV9ceqxAFfsXOGL6hZvXoKcD6+L4/WWR8iWa1s37R6tCUUGPYzQELGdwSpdZbptbJQdz83EFYOCPJASiuhXs3VYKi1gE2rQl+TvLhZwoR6tmCd0ldu8udanKZdCgc6898q5Y7GohZpvFV/ceAsd+uYsgZ119e7pNHrG2T8nWzXlY3SOQo2le2qiBdUPggxL4MWEdDJ1pWBzrQ7B3t9dmyost2QAAEpHdSTXXLksds7h2Bya1q5EgcOawV7+zjjbFd7w7Jji2X909nSsqKQcSYaqpf68/cVljnwxiFQqKLGnJoUE70VXIBSBYtNdm+RCSgMRQzipz+Kc2/eky5moUvOrhsjXEYBgmqnUS3hWr71uTlC+bonqEErG+rSQ0oQ067mDCh7nneySkfAL0XT4nQoGxzbp4IOXTpT8xoXAOtjwPDt7dSvhlYaT5+oFGeIHCatyAwm1kelO3hyblH4ZJarxJtu1/oGODN76TB9OUz9bgWj6D0Qbz2ESBHMCACZH3/3LrFDrM3g+piqNEXEoAvdSi3jcFIDUzo=
  file_glob: true
  file: implant-*
  skip_cleanup: true
  on:
    tags: true
